#!/usr/bin/env python3
"""Apply the one-artifact QA-6 verification overlay used by instrumented coverage.

The repository's canonical verification metadata intentionally remains the
strict, audited normal-build state. Android Gradle Plugin injects the JaCoCo
runtime classifier only when AndroidTest coverage is enabled. This tool adds
exactly that classifier checksum to a working copy, verifies the complete
before/after state, and refuses any other drift.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import xml.etree.ElementTree as ET

BASE_METADATA_SHA256 = "7b5ac701da2cc62cff7ea430672d25c94c187c4c0e00c7f3ad8c0c8f9b1bdb79"
EFFECTIVE_METADATA_SHA256 = "5117d79d5feb0edff805f4b65d6440577f476662586ee42c7fd297eab7368b6d"
JACOCO_RUNTIME_SHA256 = "47257ae9f22b93817eea11bc1b1fd31fc8e23049ad5dd483bfde603eaa624d0b"
JACOCO_RUNTIME_KEY = (
    "org.jacoco",
    "org.jacoco.agent",
    "0.8.11",
    "org.jacoco.agent-0.8.11-runtime.jar",
)

_POM_BLOCK = '''         <artifact name="org.jacoco.agent-0.8.11.pom">\n            <sha256 value="16e05e9f49621b87c53e69350140f3c46d42d966c67a933bdf4b063a2b1c8fc5" origin="Generated by Gradle"/>\n         </artifact>'''
_RUNTIME_BLOCK = f'''\n         <artifact name="org.jacoco.agent-0.8.11-runtime.jar">\n            <sha256 value="{JACOCO_RUNTIME_SHA256}" origin="Generated by Gradle"/>\n         </artifact>'''
_NS = {"v": "https://schema.gradle.org/dependency-verification"}


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _snapshot(data: bytes) -> tuple[str, dict[tuple[str, str, str, str], tuple[tuple[str, str | None, str | None], ...]]]:
    root = ET.fromstring(data)
    configuration = root.find("v:configuration", _NS)
    components = root.find("v:components", _NS)
    if configuration is None or components is None:
        raise ValueError("verification metadata is missing required sections")

    records: dict[
        tuple[str, str, str, str],
        tuple[tuple[str, str | None, str | None], ...],
    ] = {}
    for component in components:
        coordinate = (
            component.attrib["group"],
            component.attrib["name"],
            component.attrib["version"],
        )
        for artifact in component.findall("v:artifact", _NS):
            records[coordinate + (artifact.attrib["name"],)] = tuple(
                (
                    child.tag.rsplit("}", 1)[-1],
                    child.attrib.get("value"),
                    child.attrib.get("origin"),
                )
                for child in artifact
            )
    return ET.tostring(configuration, encoding="unicode"), records


def build_effective_metadata(base: bytes) -> bytes:
    if _sha256(base) != BASE_METADATA_SHA256:
        raise ValueError("canonical verification metadata hash does not match the audited QA-6 base")

    text = base.decode("utf-8")
    if "org.jacoco.agent-0.8.11-runtime.jar" in text:
        raise ValueError("JaCoCo runtime classifier is already present in the canonical metadata")
    if text.count(_POM_BLOCK) != 1:
        raise ValueError("expected JaCoCo 0.8.11 POM anchor was not found exactly once")

    effective = text.replace(_POM_BLOCK, _POM_BLOCK + _RUNTIME_BLOCK).encode("utf-8")
    if _sha256(effective) != EFFECTIVE_METADATA_SHA256:
        raise ValueError("effective verification metadata hash does not match the audited QA-6 overlay")

    before_configuration, before = _snapshot(base)
    after_configuration, after = _snapshot(effective)
    if before_configuration != after_configuration:
        raise ValueError("verification configuration changed")

    removed = set(before) - set(after)
    changed = {key for key in before if key in after and before[key] != after[key]}
    added = set(after) - set(before)
    if removed:
        raise ValueError(f"verification artifacts removed: {sorted(removed)!r}")
    if changed:
        raise ValueError(f"existing verification records changed: {sorted(changed)!r}")
    if added != {JACOCO_RUNTIME_KEY}:
        raise ValueError(f"unexpected verification additions: {sorted(added)!r}")

    record = after[JACOCO_RUNTIME_KEY]
    expected_record = (("sha256", JACOCO_RUNTIME_SHA256, "Generated by Gradle"),)
    if record != expected_record:
        raise ValueError(f"unexpected JaCoCo runtime verification record: {record!r}")
    return effective


def apply_overlay(metadata: Path) -> None:
    base = metadata.read_bytes()
    effective = build_effective_metadata(base)
    metadata.write_bytes(effective)
    print(f"QA6_VERIFICATION_METADATA_BASE_SHA256={BASE_METADATA_SHA256}")
    print(f"QA6_JACOCO_RUNTIME_SHA256={JACOCO_RUNTIME_SHA256}")
    print(f"QA6_VERIFICATION_METADATA_EFFECTIVE_SHA256={EFFECTIVE_METADATA_SHA256}")
    print("QA6_VERIFICATION_METADATA_ADDED=1")
    print("QA6_VERIFICATION_METADATA_REMOVED=0")
    print("QA6_VERIFICATION_METADATA_EXISTING_CHANGED=0")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("apply",))
    parser.add_argument("--metadata", type=Path, required=True)
    args = parser.parse_args()

    if args.command == "apply":
        apply_overlay(args.metadata)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
